services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: campdb
      POSTGRES_USER: campuser
      POSTGRES_PASSWORD: camppass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

#  app:
#    build: server
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/campdb
#      SPRING_DATASOURCE_USERNAME: campuser
#      SPRING_DATASOURCE_PASSWORD: camppass
#      JWT_SECRET: "z8x7c6v5b4n3m2l1k0j9h8g7f6d5s4a3p2o1i0u9y8t7r6e5w4q3z2x1c0v9b8n7m6l5k4j3h2g1f0d9s8a7p6o5i4u3y2t1"
#      FRONTEND_URL: "http://localhost:4173"
#
#  frontend:
#    build: web
#    ports:
#      - "4173:4173"
#    depends_on:
#      - app
#    environment:
#      PUBLIC_API_URL: http://app:8080

volumes:
  pgdata: 